--- #sudo pip install boto
- name: Creates ec2 instances
  hosts: localhost
  tasks:
    - name: Create instances
      ec2:
        key_name: macboo      
        instance_type: t2.micro
        image: ami-074e2d6769f445be5
        count: 3
        vpc_subnet_id: subnet-bfe913d9
        region: us-west-1
        wait: yes
        assign_public_ip: yes
        user_data:
                  #!/bin/sh
                  sudo yum install httpd php70 -y
                  service httpd start
                  chkconfig httpd on
                  
