--- #sudo pip install boto
- name: Creates ec2 instances
  hosts: localhost
  tasks:
    - name: Create instances
      ec2:
        key_name: user_ANSIBLE_TOWER      
        instance_type: t2.micro
        image: ami-0f283b180b89f6431
        count: 3
        vpc_subnet_id: subnet-b22b54c8
        region: us-east-2