---
- name: Installs ncpa agent on instances
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - set_fact:
        ansible_facts:
          pkg_mgr: yum
    - name: install nmap
      package:
        name: nmap
        state: present

