---
- name: User creation
  hosts: localhost
  tasks:
    - name: Create new IAM users with API keys
      iam:
        iam_type: user
        name: "{{ item }}"
        state: present
        password: "{{ temp_pass }}"
        access_key_state: create
      loop:
        - "{{ item }}"
        - "{{ item }}"