---
- name: IAM Create a role and attach a managed policy called "PowerUserAccess"
  hosts: localhost
  vars_files:
    - roles_vars
  tasks:
    - name: IAM add role
      iam_role:
        name: "{{name}}"                                              #Give a name to the role   Ex:MyNewRole
        state: present
        policy_name: "{{name}}"
      #- arn:aws:iam::aws:policy/PowerUserAccess
      #- arn:aws:iam::aws:policy/AdministratorAccess
      #- arn:aws:iam::aws:policy/AmazonEC2FullAccess
      #- arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess