---
- name: User creation
  hosts: localhost
  tasks:
    - name: update user with password (console access)
      iam:
        iam_type: user
        name: "{{ name }}"
        state: "{{ state }}"
        password: "{{ password }}"