---
- name: User creation
  hosts: localhost
  tasks:
    - name: update user with password (console access)
      iam:
        iam_type: user
        name: "{{ user_name }}"
        state: "{{state}}"
        password: "{{ user_pass }}"