--- #sudo pip install boto
- name: Creates ec2 instances
  hosts: localhost
  vars_files:
    - ec2_vars_CentOS_7
  tasks:
    - name: Creates CentOS7 instance
      ec2:
        key_name: "{{key_name}}"      
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        instance_tags:
          Name: Centos_7_-{{ item }}
      loop: "{{ range(1, 5 + 1)| list }}"
      wait: yes
      assign_public_ip: yes


  vars_files:
    - ec2_vars_Debian_GNU
  tasks:
    - name: Creates Debian instance
      ec2:
        key_name: "{{key_name}}"      
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        instance_tags:
          Name: Debian_-{{ item }}
      loop: "{{ range(1, 3 + 1)| list }}"
      wait: yes
      assign_public_ip: yes
      user_data:
                  #!/bin/sh
                  sudo apt-get install python -y
                  sudo pip install boto


  vars_files:
    - ec2_vars_CentOS_6
  tasks:
    - name: Creates CentOS_6 instance
      ec2:
        key_name: "{{key_name}}"      
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        instance_tags:
          Name: CentOS_6_-{{ item }}
      loop: "{{ range(1, 2 + 1)| list }}"
      wait: yes
      assign_public_ip: yes
      user_data:
                  #!/bin/sh
                  sudo apt-get install python -y
                  sudo pip install boto