- name: Creates Internet Gateway (igw)
  hosts: localhost
  tasks:
    - name: Creating igw
      ec2_vpc_igw:
        vpc_id: "{{vpc_id}}"
        name: "{{name}}"
        state: present
      register: igw