- name: Creates Internet Gateway (igw)
  hosts: localhost
  tasks:
    - name: Creating igw
      ec2_vpc_igw:
        name: "{{name}}"                        # Type a name for igw
        vpc_id: "{{vpc_id}}"                    # Add VPC ID
        state: present
        region: "{{region}}"
      register: igw