- name: Creates Internet Gateway (igw)
  hosts: localhost
  tasks:
    - name: Creating igw
      ec2_vpc_igw:
        vpc_id: "{{vpc_id}}"                    # Add the VPC ID
        resource_tags: { "Name":"Tag" }         # Change the Tag
        state: present
      register: igw